### PR TITLE
Override GMP's memory allocation functions

### LINKED ISSUE #40: Try to override default memory allocation routines
They still called for temporary allocation by ``mpn_*()`` functions.  Reproducer:
```
$ ulimit -v $((1024*64))
$ cat crash.py 
from gmp import mpz
a = mpz(249846727467293)
while True:
    a = a*a
$ python crash.py 
GNU MP: Cannot allocate memory (size=6278176)
Aborted
```

Edit: it seems only TMP_ALLOC/BALLOC are used.  It should be possible to do ``setjmp()`` *before* every (?) ``mpn_*`` call, than jump to it with ``longjmp()`` from ``allocate_function()`` on memory errors (used memory should be freed first).

### PR DESCRIPTION
**Pull request by skirpichev**
Closes #40

### CODE REVIEW

File: main.c [hunk 1]
```diff
@@ -1657,6 +1665,53 @@ static struct PyModuleDef gmp_module = {
...
+size_t idx = 0;
+
+
+static void *
+my_allocate_function(size_t size)
+{
+    if (idx > max_alloc) {
+        goto err;
+    }
+
```
Comment (rruuaanng) [inline main.c:1679]: Please add this
```
if (size == 0) {
    size = 1;
}
```
`malloc` does not handle size `0` internally, it can lead to uncontrollable memory behavior.

File: main.c [hunk 2]
```diff
@@ -1657,6 +1665,53 @@ static struct PyModuleDef gmp_module = {
...
+    void *ret = malloc(size);
+
+    if (ret == 0) {
```
Comment (rruuaanng) [inline main.c:1682]:
```suggestion
    if (ret == NULL) {
```
(Even though they are the same, I still recommend using NULL.)

File: main.c [hunk 3]
```diff
@@ -1657,6 +1665,53 @@ static struct PyModuleDef gmp_module = {
...
+        goto err;
+    }
+    mem_arr[idx] = ret;
+    idx++;
+    return ret;
+err:
```
Comment (rruuaanng) [inline main.c:1688]: Why do we need to release all the memory that has been allocated after the allocation fails?

File: main.c (hunk 1 above)
Comment (skirpichev) [reply main.c:1679]: I think it's fine.  These functions are internal.

File: main.c (hunk 3 above)
Comment (skirpichev) [reply main.c:1688]: Because we won't memory leaks, isn't?

It seems, the GMP does only allocation of temporary buffers in ``mpn_*`` functions.  So, if it fails, we de-allocate all that stuff and jump to the caller, which will raise MemoryError.

File: main.c [hunk 4]
```diff
@@ -1657,6 +1666,54 @@ static struct PyModuleDef gmp_module = {
...
+        goto err;
+    }
+
+    void *ret = malloc(size);
+
+    if (ret == NULL) {
+        goto err;
+    }
+    mem_arr[idx] = ret;
+    idx++;
```
Comment (rruuaanng) [inline main.c:1687]:
```suggestion
    mem_arr[idx++] = ret;
```

File: main.c [hunk 5]
```diff
@@ -1657,6 +1666,54 @@ static struct PyModuleDef gmp_module = {
 };
 
 
+#define max_alloc 256
```
Comment (rruuaanng) [inline main.c:1669]: Avoid the inability to distinguish between macros and variable. 
```suggestion
#define MAX_ALLOC_SIZE 256
```
Or
```suggestion
#define MAX_HEAP_SIZE 256
```

File: main.c [hunk 6]
```diff
@@ -1657,6 +1666,54 @@ static struct PyModuleDef gmp_module = {
...
+static void* mem_arr[max_alloc];
+size_t idx = 0;
```
Comment (rruuaanng) [inline main.c:1671]:
```suggestion
static size_t idx = 0;
```

File: main.c (hunk 5 above)
Comment (skirpichev) [reply main.c:1669]: This is just a draft.  Hardly this dumb structure to track allocations will survive in a final version.  So, please hold on for nitpicks, until this will be marked as ready to review.

File: main.c [hunk 7]
```diff
@@ -3,12 +3,75 @@
...
+        }
+    }
+
+    void *ret = malloc(size);
+
+    if (!ret) {
+        goto err;
+    }
+    gmp_tracker.ptrs[gmp_tracker.size] = ret;
+    gmp_tracker.size++;
```
Comment (rruuaanng) [inline main.c:43]:
```suggestion
    gmp_tracker.ptrs[gmp_tracker.size++] = ret;
```

File: main.c [hunk 8]
```diff
@@ -3,12 +3,75 @@
...
 
 static const char python_gmp_version[] = "0.1.0";
 
 
+static jmp_buf gmp_env;
+#define GMP_TRACKER_SIZE_INCR 16
+static struct {
+    size_t size;
+    size_t alloc;
+    void** ptrs;
```
[the remark this answers is not in the document]
Comment (skirpichev) [reply main.c:18]: Why?

[the remark this answers is not in the document]
Comment (rruuaanng) [reply main.c:18]: More explicit than `ptrs`? e.g. We are manipulating a heap. WDYT?

[the remark this answers is not in the document]
Comment (skirpichev) [reply main.c:18]: It's just an array.  Heap - much more complex data structure.

**Comment by skirpichev** [comment]
Following ``mpn_*()`` functions currently are used:
```
$ grep mpn_ main.c |sed 's/.*\(mpn_[^(]\+\)(.*$/\1/'|sort|uniq|awk '{ print(" - [ ] " $0)}'
```
 - [ ] mpn_add
 - [ ] mpn_add_1
 - [ ] mpn_and_n
 - [ ] mpn_andn_n
 - [ ] mpn_cmp
 - [ ] mpn_copyi
 - [ ] mpn_gcd
 - [ ] mpn_get_str
 - [ ] mpn_ior_n
 - [ ] mpn_lshift
 - [ ] mpn_mod_1
 - [ ] mpn_mul
 - [ ] mpn_popcount
 - [ ] mpn_pow_1
 - [ ] mpn_rshift
 - [ ] mpn_scan1
 - [ ] mpn_set_str
 - [ ] mpn_sizeinbase
 - [ ] mpn_sqr
 - [ ] mpn_sqrtrem
 - [ ] mpn_sub
 - [ ] mpn_sub_1
 - [ ] mpn_sub_n
 - [ ] mpn_tdiv_qr
 - [ ] mpn_xor_n

Most, those are using TMP_ALLOC/BALLOC - should be wrapped like ``mpn_sqr()`` with ``setjmp()``.

File: main.c (hunk 8 above)
[the remark this answers is not in the document]
Comment (rruuaanng) [reply main.c:18]: The minimal flash allocator for `FreeRTOS` uses an array, but it is called a `ucHeap` to make it more explicit.
